server:
  port: 19001
spring:
  application:
     name: eureka
eureka:
  instance:
    preferIpAddress: true
  server:
      enableSelfPreservation: false  #自我保护功能
      # 生产环境建议维持默认值  服务清理间隔（单位毫秒，默认是60*1000）
      #evictionIntervalTimerInMs: 20000
  client:
    registerWithEureka: false   #是否注册自身
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/



